### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by Nimava** [byungsook/deep-fluids#3]
Dear Kim, 
I run the data set generation and it worked. But when I run `python main.py` for training, I have a error message:
`KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register /home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/framework/registry.py:66)`

I remote to the Linux Red hat server with the Tensorflow 1.14.0. Could you please help me? Many thanks.

**Comment by byungsook** [comment]
would you give me more information? I haven't tested this repo with TF 1.14. Try 1.12.

**Comment by Nimava** [comment]
Thanks so much. What information do you need? When I run the main.py, I have these messages:
```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from trainer import Trainer
  File "/home/symphony/manta/trainer.py", line 9, in <module>
    from model import *
  File "/home/symphony/manta/model.py", line 3, in <module>
    from ops import *
  File "/home/symphony/manta/ops.py", line 6, in <module>
    import tensorflow.contrib.slim as slim
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/__init__.py", line 37, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 38, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/rnn/__init__.py", line 91, in <module>
    from tensorflow.contrib.rnn.python.ops.lstm_ops import *
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py", line 298, in <module>
    @ops.RegisterGradient("BlockLSTM")
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 2489, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/framework/registry.py", line 61, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register /home/symphony/.conda/envs/tf/lib/python3.7/site-packages/tensorflow_core/python/framework/registry.py:66)"

```

**Comment by byungsook** [comment]
It seems that there is a problem with importing slim. It didn't happen with TF 1.12, so I would recommend to try with different version of TF in your setting.

**Comment by Nimava** [comment]
Dear Kim,

Thanks so much. OK, I'll try. Sorry for emailing. Github suspended my
account because I live in Iran.

Sincerely,
Nima
